# Generated by Django 5.1.4 on 2025-12-06 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_document_file_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='size_mb',
        ),
    ]
