# Generated by Django 5.1.4 on 2025-12-13 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_annotations_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotations',
            name='uid',
        ),
    ]
