# Generated by Django 5.1.4 on 2025-12-15 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_annotations_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(max_length=255, upload_to='documents/'),
        ),
    ]
