# Generated by Django 5.1.4 on 2025-12-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_chatmodellogs_alter_annotations_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmartCollections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='annotations',
            name='embedding_binary',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
