# Generated by Django 5.1.4 on 2025-12-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_chatlogs_delete_chatmodellogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatlogs',
            name='content',
            field=models.JSONField(default=list),
        ),
    ]
