# Generated by Django 5.1.4 on 2025-12-20 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_chatlogs_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotations',
            name='content_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='annotations',
            name='needs_embedding',
            field=models.BooleanField(default=False),
        ),
    ]
