# Generated by Django 5.1.4 on 2025-12-20 23:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_annotations_content_hash_annotations_needs_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartcollections',
            name='annotation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='api.annotations'),
        ),
        migrations.AddField(
            model_name='smartcollections',
            name='graph_x',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='smartcollections',
            name='graph_y',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='smartcollections',
            name='major_topic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='smartcollections',
            name='sub_topic',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
