# Generated by Django 5.1.4 on 2025-12-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_smartcollections_annotation_smartcollections_graph_x_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartcollections',
            name='annotation',
        ),
        migrations.RemoveField(
            model_name='smartcollections',
            name='graph_x',
        ),
        migrations.RemoveField(
            model_name='smartcollections',
            name='graph_y',
        ),
        migrations.RemoveField(
            model_name='smartcollections',
            name='major_topic',
        ),
        migrations.RemoveField(
            model_name='smartcollections',
            name='sub_topic',
        ),
        migrations.AddField(
            model_name='annotations',
            name='major_topic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='annotations',
            name='sub_topic',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='smartcollections',
            name='annotations',
            field=models.ManyToManyField(blank=True, null=True, related_name='collections', to='api.annotations'),
        ),
    ]
