# Generated by Django 5.1.4 on 2025-12-21 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_smartcollections_annotation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotations',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='smartcollections',
            name='annotations',
            field=models.ManyToManyField(blank=True, related_name='collections', to='api.annotations'),
        ),
    ]
