# Generated by Django 5.1.4 on 2025-12-21 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_annotations_content_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartcollections',
            name='annotations',
        ),
        migrations.AddField(
            model_name='smartcollections',
            name='annotation_ids',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
