# Generated by Django 5.1.4 on 2025-12-21 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_smartcollections_annotations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartcollections',
            name='name',
        ),
    ]
