# Generated by Django 5.1.4 on 2025-12-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_smartcollections_is_ready'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='smartcollections',
            name='created_at',
        ),
        migrations.AddField(
            model_name='smartcollections',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
