# Generated by Django 5.1.4 on 2025-12-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_smartcollections_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='last_page',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
