# Generated by Django 5.1.4 on 2025-12-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_document_last_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotations',
            name='x_coordinate',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='annotations',
            name='y_coordinate',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
