# Generated by Django 5.1.4 on 2025-12-27 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_annotations_x_coordinate_annotations_y_coordinate'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartcollections',
            name='reading_recommendations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
