# Generated by Django 5.1.4 on 2025-12-29 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_smartcollections_reading_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartcollections',
            name='colors',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
