# Generated by Django 5.1.4 on 2025-12-31 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_annotations_similar_papers'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255)),
                ('idf', models.FloatField(default=0.0)),
                ('docs_containing', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='annotations',
            name='token_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='AnnotationIndex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.IntegerField()),
                ('field_boost', models.FloatField(default=1.0)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bm25_entries', to='api.annotations')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.searchterm')),
            ],
            options={
                'indexes': [models.Index(fields=['term', 'annotation'], name='api_annotat_term_id_e8205f_idx')],
                'unique_together': {('term', 'annotation')},
            },
        ),
    ]
