# Generated by Django 5.1.4 on 2026-01-23 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_searchterm_annotations_token_count_annotationindex'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='zoom_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
