# Generated by Django 5.1.4 on 2026-02-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_document_zoom_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='last_folder',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
