# Generated by Django 5.1.4 on 2026-02-25 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_folder_last_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='last_folder',
        ),
    ]
