# Generated by Django 6.0.5 on 2026-07-04 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_folder_subfolders_document_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='folder',
            options={'ordering': ['sort_order', 'name']},
        ),
    ]
