# Generated by Django 6.0.5 on 2026-08-05 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_smart_collection_jobs'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='smartcollectionjob',
            new_name='api_smartco_status_9c9a34_idx',
            old_name='api_smartco_status_375e38_idx',
        ),
    ]
