# Generated by Django 6.0.5 on 2026-09-12 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_standalone_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='standalonenote',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='api.folder'),
        ),
        migrations.AddField(
            model_name='standalonenote',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
