# This file is replacing launcher.py as the startup command
# more robust for running embeddings, django-q2 bg process, and main django server
web: python manage.py migrate && python manage.py runserver 127.0.0.1:8000

# sleep is necessary so that the entire process doesn't stop whenever funcs are finished
# uses negligble cpu/ram
embeddings: python manage.py migrate && python manage.py run_embs && python -c "import time; time.sleep(10000000)"
