const { app, BrowserWindow, dialog, ipcMain, shell } = require("electron");
const path = require("path");
const { pathToFileURL } = require("url");
const fs = require("fs");
const { spawn } = require("child_process");
const { autoUpdater } = require("electron-updater");
const log = require("electron-log");
const crypto = require("crypto");
const {
  installSessionGuards,
  installWindowGuards,
} = require("./security.cjs");
const {
  createLineParser,
  parseBackendAnnouncement,
  probeBackend,
} = require("./startup.cjs");
const { resolveBackendPath } = require("./backend-path.cjs");

// Make every renderer use Chromium's OS-level sandbox, including windows that
// may be added later. This must run before the app becomes ready.
app.enableSandbox();

autoUpdater.logger = log;
autoUpdater.autoDownload = true;
autoUpdater.autoInstallOnAppQuit = false;

function writeMcpDiscovery(port, userDataPath) {
  try {
    const discoveryPath = path.join(userDataPath, "mcp_discovery.json");
    const tokenPath = path.join(userDataPath, "mcp_token");
    let token = "";
    if (fs.existsSync(tokenPath)) {
      token = fs.readFileSync(tokenPath, "utf8").trim();
    }
    if (!token) {
      token = crypto.randomBytes(32).toString("base64url");
      fs.writeFileSync(tokenPath, token, { mode: 0o600 });
    }
    fs.writeFileSync(
      discoveryPath,
      JSON.stringify(
        {
          host: "127.0.0.1",
          port: Number(port),
          base_url: `http://127.0.0.1:${port}/api`,
          token,
          discovery_path: discoveryPath,
        },
        null,
        2,
      ),
      { mode: 0o600 },
    );
    log.info(`MCP discovery written to ${discoveryPath}`);
  } catch (error) {
    log.warn(`Could not write MCP discovery file: ${error}`);
  }
}

function shellQuote(value) {
  return `'${String(value).replace(/'/g, `'\\''`)}'`;
}

function writeMcpLauncher(userDataPath) {
  // AppImage mounts under /tmp/.mount_* are ephemeral. Claude Desktop keeps the
  // mcpServers.command path across restarts, so point it at a stable launcher that
  // remounts the AppImage (via APPIMAGE) before running `resources/backend/api mcp`.
  try {
    const appImage = process.env.APPIMAGE;
    if (!appImage || !fs.existsSync(appImage)) {
      return;
    }
    if (!String(backendPath).includes("/tmp/.mount_")) {
      return;
    }
    const launcherPath = path.join(userDataPath, "run-mcp");
    const script = `#!/usr/bin/env bash
# Auto-generated by Research Marker for Claude Desktop / Cowork MCP.
# Do not edit — reopen Research Marker to refresh after moving the AppImage.
set -euo pipefail
APPIMAGE=${shellQuote(appImage)}
BACKEND_REL='resources/backend/api'
if [[ ! -f "$APPIMAGE" ]]; then
  echo "Research Marker AppImage not found: $APPIMAGE" >&2
  echo "Open Research Marker once to refresh the MCP launcher, then restart Claude Desktop." >&2
  exit 1
fi
if [[ ! -x "$APPIMAGE" ]]; then
  chmod +x "$APPIMAGE" 2>/dev/null || true
fi
MOUNT_LOG="$(mktemp)"
cleanup() {
  if [[ -n "\${MOUNT_PID:-}" ]]; then
    kill "$MOUNT_PID" 2>/dev/null || true
    wait "$MOUNT_PID" 2>/dev/null || true
  fi
  rm -f "$MOUNT_LOG"
}
trap cleanup EXIT
"$APPIMAGE" --appimage-mount >"$MOUNT_LOG" &
MOUNT_PID=$!
MOUNT_POINT=""
for _ in $(seq 1 100); do
  if [[ -s "$MOUNT_LOG" ]]; then
    MOUNT_POINT="$(head -n 1 "$MOUNT_LOG")"
    break
  fi
  if ! kill -0 "$MOUNT_PID" 2>/dev/null; then
    break
  fi
  sleep 0.05
done
if [[ -z "$MOUNT_POINT" || ! -x "$MOUNT_POINT/$BACKEND_REL" ]]; then
  echo "Failed to mount Research Marker AppImage for MCP." >&2
  echo "Open Research Marker, then restart Claude Desktop." >&2
  exit 1
fi
"$MOUNT_POINT/$BACKEND_REL" mcp "$@"
`;
    fs.writeFileSync(launcherPath, script, { mode: 0o755 });
    log.info(`MCP launcher written to ${launcherPath}`);
  } catch (error) {
    log.warn(`Could not write MCP launcher: ${error}`);
  }
}

let mainWindow;
let splashWindow;
let sidebarWindow;
let sidebarDocumentId = null;
let pythonProcess;
let apiPort = null;
let isAppReady = false;
let updateCheckTimer = null;
let backendProgressTimer = null;
let backendStartupTimer = null;
let backendHealthTimer = null;
let rendererStartupTimer = null;
let backendHealthInFlight = false;
let backendCandidatePort = null;
let backendHealthAttempts = 0;
let hasSignaledAppReady = false;
let hasStartupFailed = false;
let isQuitting = false;
let lastSplashMessage = null;
const recentBackendLogs = [];

const SPLASH_BG = "#020204";
const BACKEND_STARTUP_TIMEOUT_MS = 120000;
const BACKEND_HEALTH_RETRY_MS = 250;
const RENDERER_STARTUP_TIMEOUT_MS = 45000;

const isDev = process.env.NODE_ENV === "development";
const useExternalBackend =
  isDev && process.env.ELECTRON_EXTERNAL_BACKEND === "1";
const devApiPort = process.env.DEV_API_PORT || "8000";
const UPDATE_CHECK_INTERVAL_MS = 4 * 60 * 60 * 1000;

let updateState = {
  status: "idle",
  currentVersion: app.getVersion(),
  availableVersion: null,
  progress: null,
  error: null,
};

const resolvePath = (devPath, prodPath) => {
  if (isDev) {
    return path.join(__dirname, devPath);
  }
  return path.join(app.getAppPath(), prodPath);
};

const backendPath = resolveBackendPath({
  isDev,
  appPath: app.getAppPath(),
  resourcesPath: process.resourcesPath,
});

function broadcastUpdateStatus() {
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send("updater:status-changed", { ...updateState });
  }
}

function setUpdateStatus(partial) {
  updateState = { ...updateState, ...partial };
  broadcastUpdateStatus();
}

function killPythonProcess() {
  if (pythonProcess) {
    log.info("[Startup] Stopping Python backend");
    pythonProcess.kill();
    pythonProcess = null;
  }
}

function installDownloadedUpdate() {
  killPythonProcess();
  autoUpdater.quitAndInstall(true, true);
}

function setupAutoUpdater() {
  autoUpdater.on("checking-for-update", () => {
    setUpdateStatus({
      status: "checking",
      error: null,
      progress: null,
    });
  });

  autoUpdater.on("update-available", (info) => {
    log.info("Update available:", info.version);
    setUpdateStatus({
      status: "available",
      availableVersion: info.version,
      error: null,
    });
  });

  autoUpdater.on("update-not-available", (info) => {
    log.info("No update available. Current:", info.version);
    setUpdateStatus({
      status: "up-to-date",
      availableVersion: null,
      progress: null,
      error: null,
    });
  });

  autoUpdater.on("download-progress", (progress) => {
    setUpdateStatus({
      status: "downloading",
      progress: {
        percent: progress.percent,
        transferred: progress.transferred,
        total: progress.total,
        bytesPerSecond: progress.bytesPerSecond,
      },
    });
  });

  autoUpdater.on("update-downloaded", (info) => {
    log.info("Update downloaded:", info.version);
    setUpdateStatus({
      status: "downloaded",
      availableVersion: info.version,
      progress: null,
      error: null,
    });

    if (!isAppReady) {
      installDownloadedUpdate();
    }
  });

  autoUpdater.on("error", (err) => {
    log.error("Auto-updater error:", err);
    if (updateState.status === "downloaded") {
      return;
    }
    setUpdateStatus({
      status: "error",
      error: err?.message || String(err),
      progress: null,
    });
  });
}

async function runUpdateCheck() {
  if (isDev) {
    setUpdateStatus({
      status: "unavailable",
      error: "Updates are disabled in development mode.",
      progress: null,
    });
    return updateState;
  }

  try {
    await autoUpdater.checkForUpdates();
  } catch (err) {
    log.error("Update check failed:", err);
    setUpdateStatus({
      status: "error",
      error: err?.message || String(err),
      progress: null,
    });
  }

  return updateState;
}

function scheduleUpdateChecks() {
  if (isDev || updateCheckTimer) {
    return;
  }

  updateCheckTimer = setInterval(() => {
    autoUpdater.checkForUpdates().catch((err) => {
      log.error("Periodic update check failed:", err);
    });
  }, UPDATE_CHECK_INTERVAL_MS);
}

function setSplashProgress(percent, message) {
  if (!splashWindow || splashWindow.isDestroyed()) {
    return;
  }

  const pct = Math.min(100, Math.max(0, percent));
  const displayMessage = message || "Initializing Research Marker...";
  const msg = JSON.stringify(displayMessage);

  if (displayMessage !== lastSplashMessage) {
    lastSplashMessage = displayMessage;
    log.info(`[Startup] Splash ${Math.round(pct)}%: ${displayMessage}`);
  }

  splashWindow.webContents
    .executeJavaScript(`window.setSplashProgress(${pct}, ${msg})`)
    .catch((error) => {
      log.warn(`[Startup] Could not update splash progress: ${error}`);
    });
}

function clearBackendStartupTimers() {
  if (backendStartupTimer) {
    clearTimeout(backendStartupTimer);
    backendStartupTimer = null;
  }
  if (backendHealthTimer) {
    clearTimeout(backendHealthTimer);
    backendHealthTimer = null;
  }
}

function formatStartupError(error) {
  if (!error) {
    return "Unknown startup error";
  }
  return error.stack || error.message || String(error);
}

async function failStartup(stage, error) {
  if (hasStartupFailed || hasSignaledAppReady || isQuitting) {
    return;
  }
  hasStartupFailed = true;
  isQuitting = true;
  clearBackendStartupTimers();
  if (rendererStartupTimer) {
    clearTimeout(rendererStartupTimer);
    rendererStartupTimer = null;
  }

  const errorText = formatStartupError(error);
  log.error(`[Startup] ${stage} failed: ${errorText}`);
  if (recentBackendLogs.length) {
    log.error(
      `[Startup] Recent backend output:\n${recentBackendLogs.slice(-12).join("\n")}`,
    );
  }

  setSplashProgress(100, "Startup failed");
  closeSplashWindow();
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.destroy();
    mainWindow = null;
  }
  killPythonProcess();

  let logPath = "the Research Marker log file";
  try {
    logPath = log.transports.file.getFile().path;
  } catch (logError) {
    log.warn(`[Startup] Could not resolve log path: ${logError}`);
  }

  const result = await dialog.showMessageBox({
    type: "error",
    title: "Research Marker could not start",
    message: `Startup stopped during ${stage}.`,
    detail:
      `${errorText}\n\nTry restarting Research Marker. If the problem continues, ` +
      `open the log and include it in a bug report.\n\nLog: ${logPath}`,
    buttons: ["Open Log", "Quit"],
    defaultId: 1,
    cancelId: 1,
    noLink: true,
  });

  if (result.response === 0) {
    shell.showItemInFolder(logPath);
  }
  app.quit();
}

function closeSplashWindow() {
  if (backendProgressTimer) {
    clearInterval(backendProgressTimer);
    backendProgressTimer = null;
  }

  if (!splashWindow || splashWindow.isDestroyed()) {
    return;
  }

  splashWindow.destroy();
  splashWindow = null;
}

function finishSplashAndShowMain(message) {
  if (hasSignaledAppReady) {
    return;
  }
  hasSignaledAppReady = true;
  if (rendererStartupTimer) {
    clearTimeout(rendererStartupTimer);
    rendererStartupTimer = null;
  }

  if (message) {
    setSplashProgress(100, message);
  }

  // Keep splash painted for a beat so progress hits 100% before reveal.
  setTimeout(() => {
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.show();
      mainWindow.focus();
      broadcastUpdateStatus();
    }
    closeSplashWindow();
  }, 160);
}

function scheduleRendererStartupTimeout() {
  if (rendererStartupTimer) {
    clearTimeout(rendererStartupTimer);
  }
  rendererStartupTimer = setTimeout(() => {
    void failStartup(
      "interface initialization",
      new Error(
        `The renderer did not signal readiness within ${RENDERER_STARTUP_TIMEOUT_MS / 1000} seconds.`,
      ),
    );
  }, RENDERER_STARTUP_TIMEOUT_MS);
}

function startBackendProgressAnimation() {
  let pct = 18;

  if (backendProgressTimer) {
    clearInterval(backendProgressTimer);
  }

  backendProgressTimer = setInterval(() => {
    if (mainWindow || pct >= 48) {
      clearInterval(backendProgressTimer);
      backendProgressTimer = null;
      return;
    }

    pct += 1;
    setSplashProgress(pct, "Starting backend...");
  }, 350);
}

function createSplashWindow() {
  log.info("[Startup] Creating splash window");
  splashWindow = new BrowserWindow({
    width: 420,
    height: 320,
    transparent: false,
    frame: true,
    alwaysOnTop: true,
    resizable: false,
    backgroundColor: SPLASH_BG,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      sandbox: true,
      webSecurity: true,
      allowRunningInsecureContent: false,
    },
  });

  const splashPath = resolvePath(
    "../app/assets/splash.html",
    "app/assets/splash.html",
  );

  log.info(`[Startup] Loading splash from ${splashPath}`);
  const splashUrl = pathToFileURL(splashPath).href;
  installSessionGuards(splashWindow.webContents.session, { isDev });
  installWindowGuards(splashWindow, splashUrl);
  splashWindow.webContents.on(
    "did-fail-load",
    (_event, errorCode, errorDescription, validatedURL, isMainFrame) => {
      if (isMainFrame) {
        void failStartup(
          "splash loading",
          new Error(
            `${validatedURL || splashUrl}: ${errorCode} ${errorDescription}`,
          ),
        );
      }
    },
  );
  splashWindow.webContents.on("render-process-gone", (_event, details) => {
    void failStartup(
      "splash renderer",
      new Error(`Splash renderer exited: ${JSON.stringify(details)}`),
    );
  });
  splashWindow.webContents.once("did-finish-load", () => {
    log.info("[Startup] Splash document loaded");
    setSplashProgress(8, "Initializing Research Marker...");
  });
  splashWindow.loadFile(splashPath).catch((error) => {
    void failStartup("splash loading", error);
  });
}

function scheduleBackendStartupTimeout() {
  clearBackendStartupTimers();
  backendStartupTimer = setTimeout(() => {
    const candidateDetail = backendCandidatePort
      ? `The backend announced port ${backendCandidatePort}, but its health check never succeeded.`
      : "Electron did not find a backend URL in the process output.";
    void failStartup(
      "backend startup",
      new Error(
        `${candidateDetail} Timed out after ${BACKEND_STARTUP_TIMEOUT_MS / 1000} seconds.`,
      ),
    );
  }, BACKEND_STARTUP_TIMEOUT_MS);
}

function markBackendReady(port, source, statusCode) {
  if (apiPort || hasStartupFailed) {
    return;
  }
  clearBackendStartupTimers();
  backendHealthInFlight = false;
  apiPort = String(port);
  log.info(
    `[Startup] Backend health check passed on port ${apiPort} ` +
      `(HTTP ${statusCode}, discovered from ${source})`,
  );
  writeMcpDiscovery(apiPort, app.getPath("userData"));

  if (backendProgressTimer) {
    clearInterval(backendProgressTimer);
    backendProgressTimer = null;
  }
  setSplashProgress(52, "Backend ready...");

  try {
    createWindow();
    isAppReady = true;
  } catch (error) {
    void failStartup("main window creation", error);
  }
}

function verifyBackendCandidate(port, source) {
  if (
    apiPort ||
    hasStartupFailed ||
    backendHealthInFlight ||
    String(port) !== backendCandidatePort
  ) {
    return;
  }

  backendHealthInFlight = true;
  backendHealthAttempts += 1;
  const attempt = backendHealthAttempts;
  probeBackend(port)
    .then(({ statusCode }) => {
      backendHealthInFlight = false;
      if (String(port) === backendCandidatePort) {
        markBackendReady(port, source, statusCode);
      } else {
        verifyBackendCandidate(backendCandidatePort, "new backend announcement");
      }
    })
    .catch((error) => {
      backendHealthInFlight = false;
      if (String(port) !== backendCandidatePort) {
        verifyBackendCandidate(backendCandidatePort, "new backend announcement");
        return;
      }
      if (attempt === 1 || attempt % 10 === 0) {
        log.warn(
          `[Startup] Backend health check attempt ${attempt} failed on port ${port}: ${error.message}`,
        );
      }
      if (!apiPort && !hasStartupFailed) {
        backendHealthTimer = setTimeout(
          () => verifyBackendCandidate(port, source),
          BACKEND_HEALTH_RETRY_MS,
        );
      }
    });
}

function considerBackendCandidate(port, source) {
  if (apiPort || hasStartupFailed) {
    return;
  }
  if (
    !/^\d+$/.test(String(port)) ||
    Number(port) < 1 ||
    Number(port) > 65535
  ) {
    log.warn(`[Startup] Ignoring invalid backend port from ${source}: ${port}`);
    return;
  }

  if (backendCandidatePort !== String(port)) {
    backendCandidatePort = String(port);
    backendHealthAttempts = 0;
    if (backendProgressTimer) {
      clearInterval(backendProgressTimer);
      backendProgressTimer = null;
    }
    if (backendHealthTimer) {
      clearTimeout(backendHealthTimer);
      backendHealthTimer = null;
    }
    log.info(
      `[Startup] Discovered backend candidate port ${backendCandidatePort} from ${source}`,
    );
    setSplashProgress(50, "Verifying backend...");
  } else {
    log.info(
      `[Startup] Confirmed backend candidate port ${backendCandidatePort} from ${source}`,
    );
  }
  verifyBackendCandidate(backendCandidatePort, source);
}

function createPythonProcess() {
  setSplashProgress(18, "Starting backend...");
  startBackendProgressAnimation();
  scheduleBackendStartupTimeout();

  const userDataPath = app.getPath("userData");
  writeMcpLauncher(userDataPath);

  log.info(`[Startup] Launching backend executable ${backendPath}`);
  log.info(`[Startup] Backend user-data directory ${userDataPath}`);

  if (!fs.existsSync(backendPath)) {
    void failStartup(
      "backend launch",
      new Error(`Bundled backend executable was not found at ${backendPath}`),
    );
    return;
  }

  const child = spawn(backendPath, [], {
    env: {
      ...process.env,
      USER_DATA_DIR: userDataPath,
      APP_DEBUG: isDev ? "true" : "false",
    },
    windowsHide: true,
  });
  pythonProcess = child;
  log.info(`[Startup] Backend process spawned with PID ${child.pid}`);

  const handleLine = (streamName, rawLine) => {
    const line = String(rawLine).trimEnd();
    if (!line) {
      return;
    }
    recentBackendLogs.push(`[${streamName}] ${line}`);
    if (recentBackendLogs.length > 80) {
      recentBackendLogs.shift();
    }
    log.info(`[Python ${streamName}] ${line}`);

    const announcement = parseBackendAnnouncement(line);
    if (announcement) {
      considerBackendCandidate(announcement.port, announcement.source);
    }
  };

  const stdoutParser = createLineParser((line) => handleLine("stdout", line));
  const stderrParser = createLineParser((line) => handleLine("stderr", line));
  child.stdout.on("data", (data) => stdoutParser.push(data));
  child.stderr.on("data", (data) => stderrParser.push(data));

  child.on("error", (error) => {
    void failStartup("backend launch", error);
  });
  child.on("close", (code, signal) => {
    stdoutParser.flush();
    stderrParser.flush();
    if (pythonProcess === child) {
      pythonProcess = null;
    }
    log.info(
      `[Startup] Backend process exited with code ${code} and signal ${signal || "none"}`,
    );
    if (!isQuitting && !hasSignaledAppReady) {
      void failStartup(
        "backend startup",
        new Error(
          `The backend exited before the interface was ready (code ${code}, signal ${signal || "none"}).`,
        ),
      );
    }
  });
}

function createWindow() {
  setSplashProgress(68, "Loading interface...");
  hasSignaledAppReady = false;
  log.info("[Startup] Creating hidden main window");

  mainWindow = new BrowserWindow({
    width: 1200,
    height: 800,
    show: false,
    frame: true,
    // Match splash so Chromium never flashes a white empty window.
    backgroundColor: SPLASH_BG,
    webPreferences: {
      preload: resolvePath("preload.cjs", "electron/preload.cjs"),
      nodeIntegration: false,
      contextIsolation: true,
      sandbox: true,
      webSecurity: true,
      allowRunningInsecureContent: false,
    },
    icon: resolvePath(
      "../app/assets/icons/icon.png",
      "app/assets/icons/icon.png",
    ),
  });
  const createdWindow = mainWindow;
  scheduleRendererStartupTimeout();

  createdWindow.webContents.on(
    "did-fail-load",
    (_event, errorCode, errorDescription, validatedURL, isMainFrame) => {
      if (isMainFrame) {
        void failStartup(
          "interface navigation",
          new Error(
            `${validatedURL || "main document"}: ${errorCode} ${errorDescription}`,
          ),
        );
      }
    },
  );
  createdWindow.webContents.on("did-start-loading", () => {
    log.info("[Startup] Main renderer started loading");
    setSplashProgress(78, "Loading interface...");
  });
  createdWindow.webContents.on("dom-ready", () => {
    log.info("[Startup] Main renderer DOM is ready");
    setSplashProgress(88, "Starting interface...");
  });
  createdWindow.webContents.on("did-finish-load", () => {
    log.info("[Startup] Main renderer document finished loading");
  });
  createdWindow.webContents.on("did-stop-loading", () => {
    log.info("[Startup] Main renderer stopped loading");
  });
  createdWindow.webContents.on("preload-error", (_event, preloadPath, error) => {
    void failStartup(
      "interface preload",
      new Error(`${preloadPath}: ${formatStartupError(error)}`),
    );
  });
  createdWindow.webContents.on("render-process-gone", (_event, details) => {
    void failStartup(
      "interface renderer",
      new Error(`Renderer exited unexpectedly: ${JSON.stringify(details)}`),
    );
  });
  createdWindow.webContents.on("console-message", (details) => {
    const level = details?.level === "error" ? "error" : "info";
    if (isDev || details?.level === "error" || details?.level === "warning") {
      log[level](
        `[Renderer] ${details?.message || "Unknown console message"}` +
          (details?.sourceId ? ` (${details.sourceId}:${details.lineNumber})` : ""),
      );
    }
  });

  // ready-to-show only means the shell can paint. The renderer's app:ready IPC
  // closes the splash after Vue has mounted and painted.
  createdWindow.once("ready-to-show", () => {
    log.info("[Startup] Main window emitted ready-to-show");
    setSplashProgress(92, "Loading library...");
  });
  createdWindow.on("unresponsive", () => {
    log.error("[Startup] Main window became unresponsive");
  });

  const closeSidebarWithMainWindow = () => {
    if (sidebarWindow && !sidebarWindow.isDestroyed()) {
      sidebarWindow.close();
    }
  };

  // Begin closing the auxiliary window as soon as the main application window
  // closes. Otherwise it can keep Electron alive as the last open window.
  createdWindow.on("close", closeSidebarWithMainWindow);
  createdWindow.on("closed", () => {
    closeSidebarWithMainWindow();
    if (mainWindow === createdWindow) {
      mainWindow = null;
    }
  });

  let applicationUrl;
  let loadPromise;
  if (isDev) {
    applicationUrl = "http://localhost:3000";
    installSessionGuards(createdWindow.webContents.session, { isDev });
    installWindowGuards(createdWindow, applicationUrl);
    log.info(`[Startup] Navigating main window to ${applicationUrl}`);
    loadPromise = createdWindow.loadURL(applicationUrl);
    createdWindow.webContents.openDevTools();
  } else {
    const applicationPath = path.join(
      app.getAppPath(),
      ".output/public/index.html",
    );
    if (!fs.existsSync(applicationPath)) {
      throw new Error(`Bundled interface was not found at ${applicationPath}`);
    }
    applicationUrl = pathToFileURL(applicationPath).href;
    installSessionGuards(createdWindow.webContents.session, { isDev });
    installWindowGuards(createdWindow, applicationUrl);
    log.info(`[Startup] Navigating main window to ${applicationUrl}#/`);
    loadPromise = createdWindow.loadFile(applicationPath, { hash: "/" });
  }

  loadPromise
    .then(() => {
      log.info(`[Startup] Main-window navigation resolved: ${applicationUrl}`);
    })
    .catch((error) => {
      void failStartup("interface navigation", error);
    });
}

function createSidebarWindow(documentId) {
  sidebarDocumentId = documentId;
  sidebarWindow = new BrowserWindow({
    width: 420,
    height: 760,
    minWidth: 300,
    minHeight: 420,
    show: false,
    title: "Sidebar — Research Marker",
    backgroundColor: SPLASH_BG,
    webPreferences: {
      preload: resolvePath("preload.cjs", "electron/preload.cjs"),
      nodeIntegration: false,
      contextIsolation: true,
      sandbox: true,
      webSecurity: true,
      allowRunningInsecureContent: false,
    },
    icon: resolvePath(
      "../app/assets/icons/icon.png",
      "app/assets/icons/icon.png",
    ),
  });

  const routeHash = `/annotate/${documentId}?sidebarPopout=1`;
  if (isDev) {
    const applicationUrl = "http://localhost:3000";
    installSessionGuards(sidebarWindow.webContents.session, { isDev });
    installWindowGuards(sidebarWindow, applicationUrl);
    const sidebarUrl = new URL(applicationUrl);
    sidebarUrl.hash = routeHash;
    sidebarWindow.loadURL(sidebarUrl.toString());
  } else {
    const applicationPath = path.join(
      app.getAppPath(),
      ".output/public/index.html",
    );
    const applicationUrl = pathToFileURL(applicationPath).href;
    installSessionGuards(sidebarWindow.webContents.session, { isDev });
    installWindowGuards(sidebarWindow, applicationUrl);
    sidebarWindow.loadFile(applicationPath, { hash: routeHash });
  }

  sidebarWindow.once("ready-to-show", () => sidebarWindow?.show());
  sidebarWindow.on("closed", () => {
    const closedDocumentId = sidebarDocumentId;
    sidebarWindow = null;
    sidebarDocumentId = null;
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.webContents.send("sidebar:popout-closed", {
        documentId: closedDocumentId,
      });
    }
  });
}

ipcMain.handle("get-api-port", (event) => {
  const sender = event.sender.id;
  log.info(`[Startup] Renderer ${sender} requested API port; returning ${apiPort}`);
  return apiPort;
});

ipcMain.handle("sidebar:pop-out", (event, payload = {}) => {
  if (!mainWindow || event.sender.id !== mainWindow.webContents.id) {
    return { ok: false, reason: "Only the main viewer can open the sidebar." };
  }

  const documentId = String(payload.documentId ?? "");
  if (!/^\d+$/.test(documentId)) {
    return { ok: false, reason: "Invalid document id." };
  }

  if (sidebarWindow && !sidebarWindow.isDestroyed()) {
    sidebarWindow.show();
    sidebarWindow.focus();
    return { ok: true, alreadyOpen: true };
  }

  createSidebarWindow(documentId);
  return { ok: true, alreadyOpen: false };
});

ipcMain.handle("sidebar:focus-popout", (event) => {
  if (!mainWindow || event.sender.id !== mainWindow.webContents.id) {
    return { ok: false };
  }
  if (!sidebarWindow || sidebarWindow.isDestroyed()) {
    return { ok: false };
  }
  sidebarWindow.show();
  sidebarWindow.focus();
  return { ok: true };
});

ipcMain.handle("sidebar:close-popout", (event) => {
  if (!sidebarWindow || sidebarWindow.isDestroyed()) {
    return { ok: false };
  }
  const isSidebarSender = event.sender.id === sidebarWindow.webContents.id;
  const isMainSender =
    mainWindow &&
    !mainWindow.isDestroyed() &&
    event.sender.id === mainWindow.webContents.id;
  if (!isSidebarSender && !isMainSender) {
    return { ok: false };
  }
  sidebarWindow.close();
  return { ok: true };
});

ipcMain.on("sidebar:reveal-annotation", (event, payload = {}) => {
  if (
    !sidebarWindow ||
    sidebarWindow.isDestroyed() ||
    event.sender.id !== sidebarWindow.webContents.id ||
    String(payload.documentId ?? "") !== sidebarDocumentId
  ) {
    return;
  }
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send("sidebar:reveal-annotation", payload);
    mainWindow.show();
  }
});

ipcMain.on("splash:progress", (event, payload = {}) => {
  if (
    !mainWindow ||
    mainWindow.isDestroyed() ||
    event.sender.id !== mainWindow.webContents.id
  ) {
    log.warn("[Startup] Ignoring splash progress from an unexpected renderer");
    return;
  }
  const percent = Number(payload.percent);
  const message = payload.message;
  if (!Number.isFinite(percent)) {
    log.warn("[Startup] Ignoring non-numeric splash progress from renderer");
    return;
  }
  log.info(
    `[Startup] Renderer progress IPC: ${Math.round(percent)}% ${message || ""}`,
  );
  setSplashProgress(percent, message);
});

ipcMain.on("app:ready", (event) => {
  if (
    !mainWindow ||
    mainWindow.isDestroyed() ||
    event.sender.id !== mainWindow.webContents.id
  ) {
    log.warn("[Startup] Ignoring app:ready from an unexpected renderer");
    return;
  }
  log.info("[Startup] Main renderer signaled app:ready");
  finishSplashAndShowMain("Ready");
});

ipcMain.handle("codex:open-auth-url", async (_event, rawUrl) => {
  let parsed;
  try {
    parsed = new URL(rawUrl);
  } catch {
    return { ok: false, reason: "Invalid authentication URL." };
  }
  const allowedHost =
    parsed.hostname === "openai.com" ||
    parsed.hostname.endsWith(".openai.com") ||
    parsed.hostname === "chatgpt.com" ||
    parsed.hostname.endsWith(".chatgpt.com");
  if (parsed.protocol !== "https:" || !allowedHost) {
    return { ok: false, reason: "Authentication URL is not allowlisted." };
  }
  await shell.openExternal(parsed.toString());
  return { ok: true };
});

ipcMain.handle("app:open-project-page", async () => {
  await shell.openExternal(
    "https://github.com/MostAardvark224/Research-Marker-OS",
  );
  return { ok: true };
});

ipcMain.handle("updater:get-status", () => {
  return { ...updateState };
});

ipcMain.handle("updater:get-version", () => {
  return app.getVersion();
});

ipcMain.handle("updater:check", async () => {
  return runUpdateCheck();
});

ipcMain.handle("updater:install", () => {
  if (updateState.status !== "downloaded") {
    return { ok: false, reason: "No downloaded update is ready to install." };
  }
  installDownloadedUpdate();
  return { ok: true };
});

ipcMain.on("restart_app", () => {
  installDownloadedUpdate();
});

app
  .whenReady()
  .then(() => {
    log.info(
      `[Startup] Electron ready (version ${app.getVersion()}, ` +
        `platform ${process.platform}, packaged ${app.isPackaged})`,
    );
    setupAutoUpdater();
    createSplashWindow();

    if (useExternalBackend) {
      log.info(
        `[Startup] Using external backend candidate at http://127.0.0.1:${devApiPort}/api`,
      );
      setSplashProgress(40, "Connecting to backend...");
      scheduleBackendStartupTimeout();
      considerBackendCandidate(devApiPort, "external backend configuration");
    } else {
      createPythonProcess();
    }

    if (isDev) {
      setUpdateStatus({
        status: "unavailable",
        error: "Updates are disabled in development mode.",
      });
    } else {
      void runUpdateCheck();
      scheduleUpdateChecks();
    }
  })
  .catch((error) => {
    void failStartup("Electron initialization", error);
  });

app.on("will-quit", () => {
  isQuitting = true;
  clearBackendStartupTimers();
  if (rendererStartupTimer) {
    clearTimeout(rendererStartupTimer);
    rendererStartupTimer = null;
  }
  if (sidebarWindow && !sidebarWindow.isDestroyed()) {
    sidebarWindow.destroy();
    sidebarWindow = null;
    sidebarDocumentId = null;
  }
  if (updateCheckTimer) {
    clearInterval(updateCheckTimer);
    updateCheckTimer = null;
  }
  killPythonProcess();
});
