const { app, BrowserWindow, ipcMain, shell } = require("electron");
const path = require("path");
const { pathToFileURL } = require("url");
const fs = require("fs");
const { spawn } = require("child_process");
const { autoUpdater } = require("electron-updater");
const log = require("electron-log");
const crypto = require("crypto");
const {
  installSessionGuards,
  installWindowGuards,
} = require("./security.cjs");

// Make every renderer use Chromium's OS-level sandbox, including windows that
// may be added later. This must run before the app becomes ready.
app.enableSandbox();

autoUpdater.logger = log;
autoUpdater.autoDownload = true;
autoUpdater.autoInstallOnAppQuit = false;

function writeMcpDiscovery(port, userDataPath) {
  try {
    const discoveryPath = path.join(userDataPath, "mcp_discovery.json");
    const tokenPath = path.join(userDataPath, "mcp_token");
    let token = "";
    if (fs.existsSync(tokenPath)) {
      token = fs.readFileSync(tokenPath, "utf8").trim();
    }
    if (!token) {
      token = crypto.randomBytes(32).toString("base64url");
      fs.writeFileSync(tokenPath, token, { mode: 0o600 });
    }
    fs.writeFileSync(
      discoveryPath,
      JSON.stringify(
        {
          host: "127.0.0.1",
          port: Number(port),
          base_url: `http://127.0.0.1:${port}/api`,
          token,
          discovery_path: discoveryPath,
        },
        null,
        2,
      ),
      { mode: 0o600 },
    );
    log.info(`MCP discovery written to ${discoveryPath}`);
  } catch (error) {
    log.warn(`Could not write MCP discovery file: ${error}`);
  }
}

function shellQuote(value) {
  return `'${String(value).replace(/'/g, `'\\''`)}'`;
}

function writeMcpLauncher(userDataPath) {
  // AppImage mounts under /tmp/.mount_* are ephemeral. Claude Desktop keeps the
  // mcpServers.command path across restarts, so point it at a stable launcher that
  // remounts the AppImage (via APPIMAGE) before running `resources/backend/api mcp`.
  try {
    const appImage = process.env.APPIMAGE;
    if (!appImage || !fs.existsSync(appImage)) {
      return;
    }
    if (!String(scriptPath).includes("/tmp/.mount_")) {
      return;
    }
    const launcherPath = path.join(userDataPath, "run-mcp");
    const script = `#!/usr/bin/env bash
# Auto-generated by Research Marker for Claude Desktop / Cowork MCP.
# Do not edit — reopen Research Marker to refresh after moving the AppImage.
set -euo pipefail
APPIMAGE=${shellQuote(appImage)}
BACKEND_REL='resources/backend/api'
if [[ ! -f "$APPIMAGE" ]]; then
  echo "Research Marker AppImage not found: $APPIMAGE" >&2
  echo "Open Research Marker once to refresh the MCP launcher, then restart Claude Desktop." >&2
  exit 1
fi
if [[ ! -x "$APPIMAGE" ]]; then
  chmod +x "$APPIMAGE" 2>/dev/null || true
fi
MOUNT_LOG="$(mktemp)"
cleanup() {
  if [[ -n "\${MOUNT_PID:-}" ]]; then
    kill "$MOUNT_PID" 2>/dev/null || true
    wait "$MOUNT_PID" 2>/dev/null || true
  fi
  rm -f "$MOUNT_LOG"
}
trap cleanup EXIT
"$APPIMAGE" --appimage-mount >"$MOUNT_LOG" &
MOUNT_PID=$!
MOUNT_POINT=""
for _ in $(seq 1 100); do
  if [[ -s "$MOUNT_LOG" ]]; then
    MOUNT_POINT="$(head -n 1 "$MOUNT_LOG")"
    break
  fi
  if ! kill -0 "$MOUNT_PID" 2>/dev/null; then
    break
  fi
  sleep 0.05
done
if [[ -z "$MOUNT_POINT" || ! -x "$MOUNT_POINT/$BACKEND_REL" ]]; then
  echo "Failed to mount Research Marker AppImage for MCP." >&2
  echo "Open Research Marker, then restart Claude Desktop." >&2
  exit 1
fi
"$MOUNT_POINT/$BACKEND_REL" mcp "$@"
`;
    fs.writeFileSync(launcherPath, script, { mode: 0o755 });
    log.info(`MCP launcher written to ${launcherPath}`);
  } catch (error) {
    log.warn(`Could not write MCP launcher: ${error}`);
  }
}

let mainWindow;
let splashWindow;
let sidebarWindow;
let sidebarDocumentId = null;
let pythonProcess;
let apiPort = null;
let isAppReady = false;
let updateCheckTimer = null;
let backendProgressTimer = null;
let splashCloseFallbackTimer = null;
let hasSignaledAppReady = false;

const SPLASH_BG = "#020204";
const SPLASH_FALLBACK_MS = 45000;

const isDev = process.env.NODE_ENV === "development";
const useExternalBackend =
  isDev && process.env.ELECTRON_EXTERNAL_BACKEND === "1";
const devApiPort = process.env.DEV_API_PORT || "8000";
const UPDATE_CHECK_INTERVAL_MS = 4 * 60 * 60 * 1000;

let updateState = {
  status: "idle",
  currentVersion: app.getVersion(),
  availableVersion: null,
  progress: null,
  error: null,
};

const resolvePath = (devPath, prodPath) => {
  if (isDev) {
    return path.join(__dirname, devPath);
  }
  return path.join(app.getAppPath(), prodPath);
};

const scriptPath = isDev
  ? path.join(app.getAppPath(), "../backend/dist/api/api")
  : path.join(process.resourcesPath, "backend", "api");

function broadcastUpdateStatus() {
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send("updater:status-changed", { ...updateState });
  }
}

function setUpdateStatus(partial) {
  updateState = { ...updateState, ...partial };
  broadcastUpdateStatus();
}

function killPythonProcess() {
  if (pythonProcess) {
    log.info("Stopping Python backend before update");
    pythonProcess.kill();
    pythonProcess = null;
  }
}

function installDownloadedUpdate() {
  killPythonProcess();
  autoUpdater.quitAndInstall(true, true);
}

function setupAutoUpdater() {
  autoUpdater.on("checking-for-update", () => {
    setUpdateStatus({
      status: "checking",
      error: null,
      progress: null,
    });
  });

  autoUpdater.on("update-available", (info) => {
    log.info("Update available:", info.version);
    setUpdateStatus({
      status: "available",
      availableVersion: info.version,
      error: null,
    });
  });

  autoUpdater.on("update-not-available", (info) => {
    log.info("No update available. Current:", info.version);
    setUpdateStatus({
      status: "up-to-date",
      availableVersion: null,
      progress: null,
      error: null,
    });
  });

  autoUpdater.on("download-progress", (progress) => {
    setUpdateStatus({
      status: "downloading",
      progress: {
        percent: progress.percent,
        transferred: progress.transferred,
        total: progress.total,
        bytesPerSecond: progress.bytesPerSecond,
      },
    });
  });

  autoUpdater.on("update-downloaded", (info) => {
    log.info("Update downloaded:", info.version);
    setUpdateStatus({
      status: "downloaded",
      availableVersion: info.version,
      progress: null,
      error: null,
    });

    if (!isAppReady) {
      installDownloadedUpdate();
    }
  });

  autoUpdater.on("error", (err) => {
    log.error("Auto-updater error:", err);
    if (updateState.status === "downloaded") {
      return;
    }
    setUpdateStatus({
      status: "error",
      error: err?.message || String(err),
      progress: null,
    });
  });
}

async function runUpdateCheck() {
  if (isDev) {
    setUpdateStatus({
      status: "unavailable",
      error: "Updates are disabled in development mode.",
      progress: null,
    });
    return updateState;
  }

  try {
    await autoUpdater.checkForUpdates();
  } catch (err) {
    log.error("Update check failed:", err);
    setUpdateStatus({
      status: "error",
      error: err?.message || String(err),
      progress: null,
    });
  }

  return updateState;
}

function scheduleUpdateChecks() {
  if (isDev || updateCheckTimer) {
    return;
  }

  updateCheckTimer = setInterval(() => {
    autoUpdater.checkForUpdates().catch((err) => {
      log.error("Periodic update check failed:", err);
    });
  }, UPDATE_CHECK_INTERVAL_MS);
}

function setSplashProgress(percent, message) {
  if (!splashWindow || splashWindow.isDestroyed()) {
    return;
  }

  const pct = Math.min(100, Math.max(0, percent));
  const msg = JSON.stringify(message || "Initializing Research Marker…");

  splashWindow.webContents
    .executeJavaScript(`window.setSplashProgress(${pct}, ${msg})`)
    .catch(() => {});
}

function closeSplashWindow() {
  if (backendProgressTimer) {
    clearInterval(backendProgressTimer);
    backendProgressTimer = null;
  }

  if (splashCloseFallbackTimer) {
    clearTimeout(splashCloseFallbackTimer);
    splashCloseFallbackTimer = null;
  }

  if (!splashWindow || splashWindow.isDestroyed()) {
    return;
  }

  splashWindow.destroy();
  splashWindow = null;
}

function finishSplashAndShowMain(message) {
  if (hasSignaledAppReady) {
    return;
  }
  hasSignaledAppReady = true;

  if (message) {
    setSplashProgress(100, message);
  }

  // Keep splash painted for a beat so progress hits 100% before reveal.
  setTimeout(() => {
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.show();
      mainWindow.focus();
      broadcastUpdateStatus();
    }
    closeSplashWindow();
  }, 160);
}

function scheduleSplashFallback() {
  if (splashCloseFallbackTimer) {
    clearTimeout(splashCloseFallbackTimer);
  }
  splashCloseFallbackTimer = setTimeout(() => {
    log.warn("Splash fallback: renderer did not signal ready in time");
    finishSplashAndShowMain("Ready");
  }, SPLASH_FALLBACK_MS);
}

function startBackendProgressAnimation() {
  let pct = 18;

  if (backendProgressTimer) {
    clearInterval(backendProgressTimer);
  }

  backendProgressTimer = setInterval(() => {
    if (mainWindow || pct >= 48) {
      clearInterval(backendProgressTimer);
      backendProgressTimer = null;
      return;
    }

    pct += 1;
    setSplashProgress(pct, "Starting backend…");
  }, 350);
}

function createSplashWindow() {
  splashWindow = new BrowserWindow({
    width: 420,
    height: 320,
    transparent: false,
    frame: true,
    alwaysOnTop: true,
    resizable: false,
    backgroundColor: SPLASH_BG,
    webPreferences: {
      nodeIntegration: false,
      contextIsolation: true,
      sandbox: true,
      webSecurity: true,
      allowRunningInsecureContent: false,
    },
  });

  const splashPath = resolvePath(
    "../app/assets/splash.html",
    "app/assets/splash.html",
  );

  log.info("Attempting to load splash from:", splashPath);
  const splashUrl = pathToFileURL(splashPath).href;
  installSessionGuards(splashWindow.webContents.session, { isDev });
  installWindowGuards(splashWindow, splashUrl);
  splashWindow.loadFile(splashPath);
  splashWindow.webContents.once("did-finish-load", () => {
    setSplashProgress(8, "Initializing Research Marker…");
  });
}

function createPythonProcess() {
  setSplashProgress(18, "Starting backend…");
  startBackendProgressAnimation();

  const userDataPath = app.getPath("userData");
  writeMcpLauncher(userDataPath);

  log.info(`Launching Python from: ${scriptPath}`);
  log.info(`Passing User Data Dir: ${userDataPath}`);

  pythonProcess = spawn(scriptPath, [], {
    env: {
      ...process.env,
      USER_DATA_DIR: userDataPath,
      APP_DEBUG: isDev ? "true" : "false",
    },
  });

  const handleLog = (data) => {
    const output = data.toString();
    log.info(`[Python]: ${output}`);

    // Only trust our explicit ready line — not uvicorn's
    // "Uvicorn running on http://127.0.0.1:PORT ..." log, which fires earlier
    // and previously opened a blank window before migrations/workers settled.
    const match = output.match(/(?:^|\n)http:\/\/127\.0\.0\.1:(\d+)[ \t]*(?:\n|$)/);

    if (match) {
      apiPort = match[1];
      log.info(`Python backend ready on port ${apiPort}`);
      writeMcpDiscovery(apiPort, userDataPath);

      if (!mainWindow) {
        if (backendProgressTimer) {
          clearInterval(backendProgressTimer);
          backendProgressTimer = null;
        }
        setSplashProgress(52, "Backend ready…");
        createWindow();
        isAppReady = true;
      }
    }
  };

  pythonProcess.stdout.on("data", handleLog);
  pythonProcess.stderr.on("data", handleLog);

  pythonProcess.on("close", (code) => {
    log.info(`Python process exited with code ${code}`);
  });
}

function createWindow() {
  setSplashProgress(68, "Loading interface…");
  hasSignaledAppReady = false;

  mainWindow = new BrowserWindow({
    width: 1200,
    height: 800,
    show: false,
    frame: true,
    // Match splash so Chromium never flashes a white empty window.
    backgroundColor: SPLASH_BG,
    webPreferences: {
      preload: resolvePath("preload.cjs", "electron/preload.cjs"),
      nodeIntegration: false,
      contextIsolation: true,
      sandbox: true,
      webSecurity: true,
      allowRunningInsecureContent: false,
    },
    icon: resolvePath(
      "../app/assets/icons/icon.png",
      "app/assets/icons/icon.png",
    ),
  });

  mainWindow.webContents.on(
    "did-fail-load",
    (_event, errorCode, errorDescription, validatedURL, isMainFrame) => {
      if (isMainFrame) {
        log.error(
          `Renderer failed to load ${validatedURL}: ${errorCode} ${errorDescription}`,
        );
      }
    },
  );
  mainWindow.webContents.on("render-process-gone", (_event, details) => {
    log.error("Renderer process exited unexpectedly:", details);
  });
  if (isDev) {
    mainWindow.webContents.on("console-message", (details) => {
      const level = details.level === "error" ? "error" : "info";
      log[level](`[Renderer] ${details.message}`);
    });
  }

  if (isDev) {
    const applicationUrl = "http://localhost:3000";
    installSessionGuards(mainWindow.webContents.session, { isDev });
    installWindowGuards(mainWindow, applicationUrl);
    mainWindow.loadURL(applicationUrl);
    mainWindow.webContents.openDevTools();
  } else {
    const applicationPath = path.join(
      app.getAppPath(),
      ".output/public/index.html",
    );
    const applicationUrl = pathToFileURL(applicationPath).href;
    installSessionGuards(mainWindow.webContents.session, { isDev });
    installWindowGuards(mainWindow, applicationUrl);
    mainWindow.loadFile(applicationPath, { hash: "/" });
  }

  mainWindow.webContents.on("did-start-loading", () => {
    setSplashProgress(78, "Loading interface…");
  });

  mainWindow.webContents.on("dom-ready", () => {
    setSplashProgress(88, "Starting interface…");
  });

  // Keep splash until the renderer finishes its first data load.
  // ready-to-show alone only means the empty shell can paint — that was the white screen.
  mainWindow.once("ready-to-show", () => {
    setSplashProgress(92, "Loading library…");
    scheduleSplashFallback();
  });

  const closeSidebarWithMainWindow = () => {
    if (sidebarWindow && !sidebarWindow.isDestroyed()) {
      sidebarWindow.close();
    }
  };

  // Begin closing the auxiliary window as soon as the main application window
  // closes. Otherwise it can keep Electron alive as the last open window.
  mainWindow.on("close", closeSidebarWithMainWindow);
  mainWindow.on("closed", () => {
    closeSidebarWithMainWindow();
    mainWindow = null;
  });
}

function createSidebarWindow(documentId) {
  sidebarDocumentId = documentId;
  sidebarWindow = new BrowserWindow({
    width: 420,
    height: 760,
    minWidth: 300,
    minHeight: 420,
    show: false,
    title: "Sidebar — Research Marker",
    backgroundColor: SPLASH_BG,
    webPreferences: {
      preload: resolvePath("preload.cjs", "electron/preload.cjs"),
      nodeIntegration: false,
      contextIsolation: true,
      sandbox: true,
      webSecurity: true,
      allowRunningInsecureContent: false,
    },
    icon: resolvePath(
      "../app/assets/icons/icon.png",
      "app/assets/icons/icon.png",
    ),
  });

  const routeHash = `/annotate/${documentId}?sidebarPopout=1`;
  if (isDev) {
    const applicationUrl = "http://localhost:3000";
    installSessionGuards(sidebarWindow.webContents.session, { isDev });
    installWindowGuards(sidebarWindow, applicationUrl);
    const sidebarUrl = new URL(applicationUrl);
    sidebarUrl.hash = routeHash;
    sidebarWindow.loadURL(sidebarUrl.toString());
  } else {
    const applicationPath = path.join(
      app.getAppPath(),
      ".output/public/index.html",
    );
    const applicationUrl = pathToFileURL(applicationPath).href;
    installSessionGuards(sidebarWindow.webContents.session, { isDev });
    installWindowGuards(sidebarWindow, applicationUrl);
    sidebarWindow.loadFile(applicationPath, { hash: routeHash });
  }

  sidebarWindow.once("ready-to-show", () => sidebarWindow?.show());
  sidebarWindow.on("closed", () => {
    const closedDocumentId = sidebarDocumentId;
    sidebarWindow = null;
    sidebarDocumentId = null;
    if (mainWindow && !mainWindow.isDestroyed()) {
      mainWindow.webContents.send("sidebar:popout-closed", {
        documentId: closedDocumentId,
      });
    }
  });
}

ipcMain.handle("get-api-port", () => {
  return apiPort;
});

ipcMain.handle("sidebar:pop-out", (event, payload = {}) => {
  if (!mainWindow || event.sender.id !== mainWindow.webContents.id) {
    return { ok: false, reason: "Only the main viewer can open the sidebar." };
  }

  const documentId = String(payload.documentId ?? "");
  if (!/^\d+$/.test(documentId)) {
    return { ok: false, reason: "Invalid document id." };
  }

  if (sidebarWindow && !sidebarWindow.isDestroyed()) {
    sidebarWindow.show();
    sidebarWindow.focus();
    return { ok: true, alreadyOpen: true };
  }

  createSidebarWindow(documentId);
  return { ok: true, alreadyOpen: false };
});

ipcMain.handle("sidebar:focus-popout", (event) => {
  if (!mainWindow || event.sender.id !== mainWindow.webContents.id) {
    return { ok: false };
  }
  if (!sidebarWindow || sidebarWindow.isDestroyed()) {
    return { ok: false };
  }
  sidebarWindow.show();
  sidebarWindow.focus();
  return { ok: true };
});

ipcMain.handle("sidebar:close-popout", (event) => {
  if (!sidebarWindow || sidebarWindow.isDestroyed()) {
    return { ok: false };
  }
  const isSidebarSender = event.sender.id === sidebarWindow.webContents.id;
  const isMainSender =
    mainWindow &&
    !mainWindow.isDestroyed() &&
    event.sender.id === mainWindow.webContents.id;
  if (!isSidebarSender && !isMainSender) {
    return { ok: false };
  }
  sidebarWindow.close();
  return { ok: true };
});

ipcMain.on("sidebar:reveal-annotation", (event, payload = {}) => {
  if (
    !sidebarWindow ||
    sidebarWindow.isDestroyed() ||
    event.sender.id !== sidebarWindow.webContents.id ||
    String(payload.documentId ?? "") !== sidebarDocumentId
  ) {
    return;
  }
  if (mainWindow && !mainWindow.isDestroyed()) {
    mainWindow.webContents.send("sidebar:reveal-annotation", payload);
    mainWindow.show();
  }
});

ipcMain.on("splash:progress", (_event, payload = {}) => {
  const percent = Number(payload.percent);
  const message = payload.message;
  if (!Number.isFinite(percent)) {
    return;
  }
  setSplashProgress(percent, message);
});

ipcMain.on("app:ready", () => {
  log.info("Renderer signaled ready");
  finishSplashAndShowMain("Ready");
});

ipcMain.handle("codex:open-auth-url", async (_event, rawUrl) => {
  let parsed;
  try {
    parsed = new URL(rawUrl);
  } catch {
    return { ok: false, reason: "Invalid authentication URL." };
  }
  const allowedHost =
    parsed.hostname === "openai.com" ||
    parsed.hostname.endsWith(".openai.com") ||
    parsed.hostname === "chatgpt.com" ||
    parsed.hostname.endsWith(".chatgpt.com");
  if (parsed.protocol !== "https:" || !allowedHost) {
    return { ok: false, reason: "Authentication URL is not allowlisted." };
  }
  await shell.openExternal(parsed.toString());
  return { ok: true };
});

ipcMain.handle("app:open-project-page", async () => {
  await shell.openExternal(
    "https://github.com/MostAardvark224/Research-Marker-OS",
  );
  return { ok: true };
});

ipcMain.handle("updater:get-status", () => {
  return { ...updateState };
});

ipcMain.handle("updater:get-version", () => {
  return app.getVersion();
});

ipcMain.handle("updater:check", async () => {
  return runUpdateCheck();
});

ipcMain.handle("updater:install", () => {
  if (updateState.status !== "downloaded") {
    return { ok: false, reason: "No downloaded update is ready to install." };
  }
  installDownloadedUpdate();
  return { ok: true };
});

ipcMain.on("restart_app", () => {
  installDownloadedUpdate();
});

app.whenReady().then(() => {
  setupAutoUpdater();
  createSplashWindow();

  if (useExternalBackend) {
    apiPort = devApiPort;
    log.info(`Using external backend at http://127.0.0.1:${apiPort}/api`);
    setSplashProgress(40, "Connecting to backend…");
    createWindow();
    isAppReady = true;
  } else {
    createPythonProcess();
  }

  if (isDev) {
    setUpdateStatus({
      status: "unavailable",
      error: "Updates are disabled in development mode.",
    });
  } else {
    runUpdateCheck();
    scheduleUpdateChecks();
  }
});

app.on("will-quit", () => {
  if (sidebarWindow && !sidebarWindow.isDestroyed()) {
    sidebarWindow.destroy();
    sidebarWindow = null;
    sidebarDocumentId = null;
  }
  if (updateCheckTimer) {
    clearInterval(updateCheckTimer);
    updateCheckTimer = null;
  }
  killPythonProcess();
});
