# Generated by Django 5.1.4 on 2025-12-06 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_document_size_mb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
