# Generated by Django 5.1.4 on 2025-12-10 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_annotations'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='searchable',
            field=models.BooleanField(default=False),
        ),
    ]
