# Generated by Django 5.1.4 on 2025-12-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_document_searchable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annotations',
            name='content',
        ),
        migrations.AddField(
            model_name='annotations',
            name='highlight_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='annotations',
            name='notepad',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotations',
            name='sticky_note_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='annotations',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
