# Generated by Django 5.1.4 on 2025-12-17 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotations',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
