# Generated by Django 5.1.4 on 2025-12-20 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_chatlogs_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatlogs',
            name='created_at',
        ),
    ]
