# Generated by Django 5.1.4 on 2025-12-22 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_smartcollections_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartcollections',
            name='is_ready',
            field=models.BooleanField(default=False),
        ),
    ]
