# Generated by Django 5.1.4 on 2025-12-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_smartcollections_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotations',
            name='similar_papers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
